<?php

add_action('wp_enqueue_scripts', function() {
    wp_enqueue_style('main', get_stylesheet_directory_uri() . '/assets/dist/main.css', [], '1.0.0', 'all');
    wp_enqueue_script('main', get_stylesheet_directory_uri() . '/assets/dist/main.js', [], '1.0.0', true);
});


register_nav_menu("blog-theme-menu", "the primary menu used throught blog-theme");

// Add bootstraps nav class to wordpress navbar items
function bootstrap_nav_item($classes, $item, $args, $depth)
{
    $classes[] = "nav-item";
    return $classes;
}

add_filter('nav_menu_css_class', 'bootstrap_nav_item', 10, 4);

function bootstrap_nav_link($atts, $item, $args, $depth)
{
    $atts['class'] = "nav-link";
    return $atts;
}

add_filter('nav_menu_link_attributes', 'bootstrap_nav_link', 10, 4);

// access autogenerated excerpt
add_filter( 'the_excerpt', function ( $excerpt ) {
    return has_excerpt() ?
        'Has custom excerpt: ' . $excerpt :
        'Automatic excerpt: ' . $excerpt;
} );

add_theme_support('post-thumbnails');

function default_thumbnail($width, $height) {
    print('<img class="img-fluid" width="' . $width . '" ' . 'height="' . $height . '" ' . 'src="' . get_bloginfo('template_url') . '/assets/src/images/defaultthumbnail.jpg' . '">');
}

function get_image($src ,$width, $height) {
    print('<img class="img-fluid" width="' . $width . '" ' . 'height="' . $height . '" ' . 'src="' . get_bloginfo('template_url') . '/assets/src/images/' . $src . '">');
}
